//! The OPML parser on exports in each big reader's style (invented feeds),
//! the export round trip, matching, and the paced import loop.

use std::sync::Mutex;
use std::sync::atomic::AtomicBool;
use std::time::{Duration, Instant};

use super::*;

/// Feedly: `type="rss"`, `text` and `title`, folders by category, entities.
const FEEDLY: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
    <head>
        <title>Ada subscriptions in feedly Cloud</title>
    </head>
    <body>
        <outline text="Tech" title="Tech">
            <outline type="rss" text="Ada &amp; Co" title="Ada &amp; Co" xmlUrl="https://ada.example.com/feed.xml" htmlUrl="https://ada.example.com/"/>
            <outline type="rss" text="Rue&#8217;s notes" title="Rue&#8217;s notes" xmlUrl="https://rue.example.org/rss" htmlUrl="https://rue.example.org"/>
        </outline>
        <outline text="Cooking" title="Cooking">
            <outline type="rss" text="Kale &amp;amp; More" title="Kale &amp;amp; More" xmlUrl="https://kale.example.net/atom.xml" htmlUrl="https://kale.example.net"/>
        </outline>
    </body>
</opml>
"#;

/// NetNewsWire: OPML 1.1, no `type` on some, `title` missing (text only),
/// nested folders, unescaped `'` quoting.
const NETNEWSWIRE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- OPML generated by NetNewsWire -->
<opml version="1.1">
	<head>
		<title>Subscriptions-OnMyMac.opml</title>
	</head>
<body>
	<outline text="Blogs" title="Blogs">
		<outline text="Friends">
			<outline text='Ozzie writes' xmlUrl='https://ozzie.example.com/index.xml' htmlUrl='https://ozzie.example.com/'/>
		</outline>
		<outline text="Pim" type="rss" version="RSS" xmlUrl="https://pim.example.org/feed/"/>
	</outline>
	<outline text="Loose" xmlUrl="https://loose.example.com/feed.json" htmlUrl="https://loose.example.com"/>
</body>
</opml>"#;

/// Inoreader: `type="rss"` everywhere, `&nbsp;` and `&eacute;` (HTML
/// entities), a duplicate across folders.
const INOREADER: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
  <head>
    <title>Subscriptions from Inoreader [https://www.inoreader.com]</title>
  </head>
  <body>
    <outline text="News" title="News">
      <outline text="Caf&eacute;&nbsp;Daily" title="Caf&eacute;&nbsp;Daily" type="rss" xmlUrl="https://cafe.example.com/rss.xml" htmlUrl="https://cafe.example.com/"/>
    </outline>
    <outline text="Also" title="Also">
      <outline text="Café again" title="Café again" type="rss" xmlUrl="http://www.cafe.example.com/rss.xml/" htmlUrl="https://cafe.example.com/"/>
    </outline>
  </body>
</opml>"#;

/// Miniflux: OPML 2.0, `type="rss"`, `title` with no `text`, categories.
const MINIFLUX: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  <head>
    <title>Miniflux</title>
    <dateCreated>Fri, 02 Oct 2026 10:00:00 UTC</dateCreated>
  </head>
  <body>
    <outline text="All">
      <outline title="Atom One" text="Atom One" xmlUrl="https://atom.example.org/atom" htmlUrl="https://atom.example.org/" type="atom"></outline>
      <outline title="No Text" xmlUrl="https://notext.example.org/rss" htmlUrl="https://notext.example.org/" type="rss"></outline>
    </outline>
  </body>
</opml>"#;

/// Reeder: flat, no head title, a site-only outline, uppercase attributes.
const REEDER: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0"><head/><body>
<outline TEXT="Shouty" XMLURL="https://shouty.example.com/feed"/>
<outline text="Just a site" htmlUrl="https://site.example.com/"/>
<outline text=""  xmlUrl="https://bare.example.net/rss.xml" />
</body></opml>"#;

fn titles(p: &Parsed) -> Vec<&str> {
    p.feeds.iter().map(|f| f.title.as_str()).collect()
}

#[test]
fn feedly_folders_and_entities() {
    let p = parse(FEEDLY).unwrap();
    assert_eq!(titles(&p), ["Ada & Co", "Rue’s notes", "Kale & More"]);
    assert_eq!(p.feeds[0].folder.as_deref(), Some("Tech"));
    assert_eq!(p.feeds[2].folder.as_deref(), Some("Cooking"));
    assert_eq!(p.feeds[1].xml_url, "https://rue.example.org/rss");
    assert_eq!(
        p.feeds[1].html_url.as_deref(),
        Some("https://rue.example.org")
    );
}

#[test]
fn netnewswire_nested_folders_and_missing_type() {
    let p = parse(NETNEWSWIRE).unwrap();
    assert_eq!(titles(&p), ["Ozzie writes", "Pim", "Loose"]);
    assert_eq!(p.feeds[0].folder.as_deref(), Some("Blogs / Friends"));
    assert_eq!(p.feeds[1].folder.as_deref(), Some("Blogs"));
    assert_eq!(p.feeds[2].folder, None);
}

#[test]
fn inoreader_html_entities_and_duplicates() {
    let p = parse(INOREADER).unwrap();
    // `&nbsp;` is whitespace, so it collapses to a plain space.
    assert_eq!(titles(&p), ["Café Daily"]);
    assert_eq!(p.duplicates, 1, "http/www/trailing-slash variant collapses");
}

#[test]
fn miniflux_atom_type_and_title_only() {
    let p = parse(MINIFLUX).unwrap();
    assert_eq!(titles(&p), ["Atom One", "No Text"]);
    assert!(p.feeds.iter().all(|f| f.folder.as_deref() == Some("All")));
}

#[test]
fn reeder_flat_uppercase_and_site_only() {
    let p = parse(REEDER).unwrap();
    assert_eq!(titles(&p), ["Shouty", "bare.example.net"]);
    assert_eq!(p.without_feed, 1);
}

#[test]
fn bom_utf16_and_windows_1252() {
    let mut bom = vec![0xEF, 0xBB, 0xBF];
    bom.extend_from_slice(REEDER.as_bytes());
    assert_eq!(parse_bytes(&bom).unwrap().feeds.len(), 2);

    let mut utf16 = vec![0xFF, 0xFE];
    for u in MINIFLUX.encode_utf16() {
        utf16.extend_from_slice(&u.to_le_bytes());
    }
    assert_eq!(
        titles(&parse_bytes(&utf16).unwrap()),
        ["Atom One", "No Text"]
    );

    // Says UTF-8, is Windows-1252: "Caf\xe9 \x93Q\x94".
    let mut cp =
        br#"<?xml version="1.0" encoding="UTF-8"?><opml><body><outline text="Caf"#.to_vec();
    cp.extend_from_slice(&[0xE9, b' ', 0x93, b'Q', 0x94]);
    cp.extend_from_slice(br#"" xmlUrl="https://cp.example.com/rss"/></body></opml>"#);
    assert_eq!(titles(&parse_bytes(&cp).unwrap()), ["Café “Q”"]);
}

#[test]
fn junk_comments_and_quoted_angle_brackets() {
    let xml = r#"<opml><body>
      <!-- <outline text="commented out" xmlUrl="https://no.example.com/rss"/> -->
      <outline text="a > b" xmlUrl="https://gt.example.com/rss"/>
      <outline text="evil" xmlUrl="javascript:alert(1)"/>
      <outlines text="not one" xmlUrl="https://no.example.com/x"/>
      <outline text="ok" xmlUrl="HTTPS://case.example.com/rss"/>
      <outline text="unterminated
    </body></opml> junk <<<"#;
    let p = parse(xml).unwrap();
    assert_eq!(titles(&p), ["a > b", "ok"]);
}

#[test]
fn refusals_have_clear_messages() {
    assert_eq!(parse("<html>hello</html>"), Err(OpmlError::NotOpml));
    assert_eq!(
        parse("<opml><body><outline text=\"x\"/></body></opml>"),
        Err(OpmlError::NoFeeds)
    );
    let big = vec![b' '; MAX_FILE_BYTES + 1];
    let e = parse_bytes(&big).unwrap_err();
    assert!(matches!(e, OpmlError::TooBig(_)));
    assert!(e.to_string().contains("at most 5 MB"), "{e}");
    let many: String = (0..=MAX_FEEDS)
        .map(|i| format!("<outline text=\"f{i}\" xmlUrl=\"https://f{i}.example.com/rss\"/>"))
        .collect();
    let e = parse(&format!("<opml><body>{many}</body></opml>")).unwrap_err();
    assert_eq!(e, OpmlError::TooMany(MAX_FEEDS + 1));
    assert!(e.to_string().contains("at most 2000"), "{e}");
}

fn sub(id: &str, kind: SubscriptionKind, origin: &str, feed: &str, title: &str) -> Subscription {
    Subscription {
        id: id.into(),
        kind,
        origin: origin.into(),
        feed_url: feed.into(),
        title: title.into(),
        status: "active".into(),
        in_blogroll: false,
        title_follows_source: true,
    }
}

#[test]
fn already_followed_by_feed_or_blyg_origin() {
    let subs = vec![
        sub(
            "s1",
            SubscriptionKind::Rss,
            "https://ada.example.com/feed.xml",
            "https://ada.example.com/feed.xml",
            "Ada",
        ),
        sub(
            "s2",
            SubscriptionKind::Blyg,
            "https://kit.example.org/blyg/",
            "https://kit.example.org/blyg/feed.xml",
            "Kit",
        ),
    ];
    let feed = |x: &str, h: Option<&str>| OpmlFeed {
        title: "t".into(),
        xml_url: x.into(),
        html_url: h.map(Into::into),
        folder: None,
    };
    assert_eq!(
        followed(&feed("http://www.ADA.example.com/feed.xml/", None), &subs).map(|s| &*s.id),
        Some("s1")
    );
    // A blyg's other feed (its Atom, say) is still that blyg.
    assert_eq!(
        followed(&feed("https://kit.example.org/blyg/atom.xml", None), &subs).map(|s| &*s.id),
        Some("s2")
    );
    assert!(followed(&feed("https://kit.example.org/other/rss", None), &subs).is_none());
    assert!(followed(&feed("https://new.example.net/rss", None), &subs).is_none());
}

#[test]
fn export_round_trips() {
    let subs = vec![
        sub(
            "s1",
            SubscriptionKind::Blyg,
            "https://kit.example.org/blyg/",
            "https://kit.example.org/blyg/feed.xml",
            "Kit & \"Co\" <3",
        ),
        sub(
            "s2",
            SubscriptionKind::Rss,
            "https://ada.example.com/feed.xml?x=1&y=2",
            "https://ada.example.com/feed.xml?x=1&y=2",
            "",
        ),
    ];
    let xml = export(&subs);
    assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<opml version=\"2.0\">"));
    assert!(xml.contains("type=\"rss\""));
    let p = parse(&xml).unwrap();
    let got: Vec<(&str, &str, Option<&str>)> = p
        .feeds
        .iter()
        .map(|f| (f.title.as_str(), f.xml_url.as_str(), f.html_url.as_deref()))
        .collect();
    assert_eq!(
        got,
        [
            (
                "Kit & \"Co\" <3",
                "https://kit.example.org/blyg/feed.xml",
                Some("https://kit.example.org/blyg/")
            ),
            (
                "https://ada.example.com/feed.xml?x=1&y=2",
                "https://ada.example.com/feed.xml?x=1&y=2",
                Some("https://ada.example.com/feed.xml?x=1&y=2")
            ),
        ]
    );
    // Every exported feed reads back as already followed.
    assert!(p.feeds.iter().all(|f| followed(f, &subs).is_some()));
    assert_eq!(export(&[]).matches("<outline").count(), 0);
}

// ---------------------------------------------------------------- the run

fn feeds(urls: &[&str]) -> Vec<OpmlFeed> {
    urls.iter()
        .map(|u| OpmlFeed {
            title: u.to_string(),
            xml_url: u.to_string(),
            html_url: None,
            folder: None,
        })
        .collect()
}

fn quick() -> Pace {
    Pace {
        concurrency: 2,
        interval: Duration::ZERO,
        max_waits: 2,
    }
}

fn rejected(status: u16, message: &str) -> CoreError {
    CoreError::Rejected {
        status,
        message: message.into(),
        details: vec![],
    }
}

/// The answer the server gives for each URL, as the API client maps it.
fn answer(url: &str) -> crate::Result<Subscription> {
    match url {
        u if u.contains("dead") => Err(CoreError::Rejected {
            status: 422,
            message: "could not resolve this URL to a blyg or a feed".into(),
            details: vec!["tried 4 addresses".into()],
        }),
        u if u.contains("old") => Err(rejected(409, "already subscribed to Old")),
        u if u.contains("bad") => Err(rejected(400, "url required")),
        u => Ok(sub(&format!("id-{u}"), SubscriptionKind::Rss, u, u, "Feed")),
    }
}

#[test]
fn each_answer_maps_and_only_added_ones_are_filed() {
    let fs = feeds(&[
        "https://a/rss",
        "https://old/rss",
        "https://dead/rss",
        "https://bad/rss",
    ]);
    let filed = Mutex::new(vec![]);
    let seen = Mutex::new(vec![]);
    let r = run_paced(
        &fs,
        &quick(),
        &AtomicBool::new(false),
        &answer,
        &|id| filed.lock().unwrap().push(id.to_string()),
        &|p| seen.lock().unwrap().push(p),
    );
    assert_eq!(
        r[0],
        Some(Outcome::Added {
            id: "id-https://a/rss".into(),
            title: "Feed".into()
        })
    );
    assert_eq!(r[1], Some(Outcome::AlreadyFollowing));
    assert_eq!(
        r[2],
        Some(Outcome::Failed {
            kind: FailKind::NotAFeed,
            reason: "could not resolve this URL to a blyg or a feed (tried 4 addresses)".into()
        })
    );
    assert!(matches!(
        &r[3],
        Some(Outcome::Failed { kind: FailKind::Refused, reason }) if reason == "url required"
    ));
    assert_eq!(*filed.lock().unwrap(), ["id-https://a/rss"]);
    assert_eq!(seen.lock().unwrap().len(), 4);
    let s = Summary::of(&r);
    assert_eq!(s.line(), "1 added, 1 already followed, 2 failed");
    assert_eq!(s.failed[0].0, 2);
}

#[test]
fn a_429_waits_out_retry_after_then_tries_the_same_feed_again() {
    let calls = Mutex::new(0);
    let seen = Mutex::new(vec![]);
    let started = Instant::now();
    let r = run_paced(
        &feeds(&["https://a/rss"]),
        &quick(),
        &AtomicBool::new(false),
        &|u| {
            let mut n = calls.lock().unwrap();
            *n += 1;
            if *n == 1 {
                Err(CoreError::RateLimited { retry_after: 1 })
            } else {
                answer(u)
            }
        },
        &|_| {},
        &|p| seen.lock().unwrap().push(p),
    );
    assert!(started.elapsed() >= Duration::from_millis(950));
    assert_eq!(*calls.lock().unwrap(), 2);
    assert!(matches!(r[0], Some(Outcome::Added { .. })));
    assert_eq!(seen.lock().unwrap()[0], Progress::Waiting { seconds: 1 });
}

#[test]
fn pacing_spaces_the_starts() {
    let starts = Mutex::new(vec![]);
    let pace = Pace {
        concurrency: 3,
        interval: Duration::from_millis(60),
        max_waits: 0,
    };
    run_paced(
        &feeds(&["https://a/1", "https://a/2", "https://a/3", "https://a/4"]),
        &pace,
        &AtomicBool::new(false),
        &|u| {
            starts.lock().unwrap().push(Instant::now());
            answer(u)
        },
        &|_| {},
        &|_| {},
    );
    let mut s = starts.into_inner().unwrap();
    s.sort();
    // Each start has its own slot 60 ms after the last (a thread may wake a
    // little late, so pairs can be closer; the whole run can't be).
    let span = s[3] - s[0];
    assert!(span >= Duration::from_millis(150), "{span:?}");
    for w in s.windows(2) {
        assert!(
            w[1] - w[0] >= Duration::from_millis(30),
            "{:?}",
            w[1] - w[0]
        );
    }
}

#[test]
fn cancel_stops_after_the_one_in_flight() {
    let cancel = AtomicBool::new(false);
    let pace = Pace {
        concurrency: 1,
        interval: Duration::ZERO,
        max_waits: 0,
    };
    let r = run_paced(
        &feeds(&["https://a/1", "https://a/2", "https://a/3"]),
        &pace,
        &cancel,
        &|u| {
            cancel.store(true, std::sync::atomic::Ordering::Relaxed);
            answer(u)
        },
        &|_| {},
        &|_| {},
    );
    assert!(
        matches!(r[0], Some(Outcome::Added { .. })),
        "what's done stays done"
    );
    assert_eq!(r[1..], [None, None]);
    assert_eq!(
        Summary::of(&r).line(),
        "1 added, 0 already followed, 0 failed, 2 not tried"
    );
}

#[test]
fn import_folder_is_made_once_and_reused_on_real_sqlite() {
    let dir = tempfile::tempdir().unwrap();
    let opts = crate::SyncOptions {
        start_worker: false,
        ..Default::default()
    };
    let b = crate::LiveBackend::open_with(
        dir.path(),
        "http://127.0.0.1:9",
        crate::api::auth::Credential::Token("t".into()),
        opts,
    )
    .unwrap();
    b.create_folder("Mine").unwrap();
    let f = import_folder(&b).unwrap();
    assert_eq!(f.name, IMPORT_FOLDER);
    assert_eq!(import_folder(&b).unwrap().id, f.id);
    b.rename_folder(&f.id, "imported FEEDS").unwrap();
    assert_eq!(
        import_folder(&b).unwrap().id,
        f.id,
        "any case is the same folder"
    );
    assert_eq!(b.folders().len(), 2);
    // Filing by id holds before the subscription is in the local list.
    b.set_subscription_folder("sub-later", Some(&f.id)).unwrap();
    assert_eq!(b.subscription_folders().get("sub-later"), Some(&f.id));
}
